In [9]:
import pandas as pd

In [10]:
# tufe_raw.csv ön işleme

tufe = pd.read_csv("tufe_raw.csv", sep=";", encoding="utf-8-sig", decimal=",")

tufe["Tarih"] = pd.to_datetime(tufe["Tarih"], format="%Y-%m")
tufe["TÜFE_Yıllık_Değişim"] = pd.to_numeric(tufe["TÜFE_Yıllık_Değişim"], errors="coerce")
tufe["TÜFE_Aylık_Değişim"] = pd.to_numeric(tufe["TÜFE_Aylık_Değişim"], errors="coerce")

tufe = tufe[["Tarih", "TÜFE_Yıllık_Değişim", "TÜFE_Aylık_Değişim"]]
tufe = tufe[tufe["Tarih"] >= "2021-01-01"]

tufe.head()

       Tarih  TÜFE_Yıllık_Değişim  TÜFE_Aylık_Değişim
0 2021-01-01                14.97                1.68
1 2021-02-01                15.61                0.91
2 2021-03-01                16.19                1.08
3 2021-04-01                17.14                1.68
4 2021-05-01                16.59                0.89

In [11]:
# politika_faiz_raw.csv ön işleme

politika = pd.read_csv("politika_faiz_raw.csv", sep=";", encoding="utf-8-sig", decimal=",")

politika["Tarih"] = pd.to_datetime(politika["Tarih"], format="%Y-%m")
politika["Politika_Faizi"] = pd.to_numeric(politika["POLFAIZ_TUR"], errors="coerce")

politika = politika[["Tarih", "Politika_Faizi"]]
politika = politika[politika["Tarih"] >= "2021-01-01"]

politika.head()

        Tarih  Politika_Faizi
12 2021-01-01            17.0
13 2021-02-01            17.0
14 2021-03-01            19.0
15 2021-04-01            19.0
16 2021-05-01            19.0

In [12]:
# mevduat_faiz_raw.csv ön işleme

mevduat = pd.read_csv("mevduat_faiz_raw.csv", sep=";", encoding="utf-8-sig", decimal=",")

mevduat["Tarih"] = pd.to_datetime(mevduat["Tarih"], format="%d.%m.%Y")
mevduat["Mevduat_Faizi"] = pd.to_numeric(mevduat["Mevduat_Yüzde"], errors="coerce")

mevduat = mevduat[["Tarih", "Mevduat_Faizi"]]
mevduat = mevduat[mevduat["Tarih"] >= "2021-01-01"]

# haftalık veriyi aylık ortalamaya çevirme
mevduat["Tarih"] = mevduat["Tarih"].values.astype("datetime64[M]")
mevduat = mevduat.groupby("Tarih", as_index=False)["Mevduat_Faizi"].mean()

# virgülden sonra 2 basamak olacak şekilde yuvarlama
mevduat["Mevduat_Faizi"] = mevduat["Mevduat_Faizi"].round(2)

mevduat.head()

       Tarih  Mevduat_Faizi
0 2021-01-01          16.36
1 2021-02-01          16.22
2 2021-03-01          16.81
3 2021-04-01          17.78
4 2021-05-01          17.89

In [13]:
# dolar_kuru_raw.csv ön işleme

dolar = pd.read_csv("dolar_kuru_raw.csv", sep=";", encoding="utf-8-sig", decimal=",")

dolar["Tarih"] = pd.to_datetime(dolar["Tarih"], format="%Y-%m")
dolar["USDTRY"] = pd.to_numeric(dolar["USD_YTL"], errors="coerce")

dolar = dolar[["Tarih", "USDTRY"]]
dolar = dolar[dolar["Tarih"] >= "2021-01-01"]

dolar.head()

       Tarih  USDTRY
0 2021-01-01    7.39
1 2021-02-01    7.07
2 2021-03-01    7.63
3 2021-04-01    8.16
4 2021-05-01    8.34

In [14]:
# altin_raw.csv ön işleme
altin = pd.read_csv("altın_raw.csv", sep=";", encoding="utf-8-sig", decimal=",")
altin["Tarih"] = pd.to_datetime(altin["Tarih"], format="%Y-%m")

# altın fiyatını temizleyip sayıya çevirme
altin["Gram_Altın"] = (
    altin["ALTIN_YTL"]
    .astype(str)
    .str.replace(".", "", regex=False)   # binlik ayırıcıyı kaldır
    .str.replace(",", ".", regex=False)  # ondalık ayırıcıyı düzelt
    .pipe(pd.to_numeric, errors="coerce")
)

# sadece gerekli sütunlar
altin = altin[["Tarih", "Gram_Altın"]]
altin = altin[altin["Tarih"] >= "2021-01-01"]

altin.tail()

        Tarih  Gram_Altın
57 2025-10-01     5744.17
58 2025-11-01     5764.62
59 2025-12-01     6030.79
60 2026-01-01     6817.67
61 2026-02-01     7515.92

In [15]:
# bist100_raw.csv ön işleme

bist = pd.read_csv("bist100_raw.csv", encoding="utf-8-sig")

bist["Tarih"] = pd.to_datetime(bist["Tarih"], format="%d.%m.%Y")
bist["BIST100"] = (
    bist["Şimdi"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
)

bist = bist[["Tarih", "BIST100"]]
bist = bist[bist["Tarih"] >= "2021-01-01"]

bist.head()

       Tarih   BIST100
0 2026-03-01  12698.19
1 2026-02-01  13717.81
2 2026-01-01  13838.29
3 2025-12-01  11261.52
4 2025-11-01  10898.70

In [16]:
# brent_petrol_raw.csv ön işleme

brent = pd.read_csv("brent_petrol_raw.csv", encoding="utf-8-sig")

brent["Tarih"] = pd.to_datetime(brent["Tarih"], format="%d.%m.%Y")
brent["Brent_Petrol"] = (
    brent["Şimdi"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
)

brent = brent[["Tarih", "Brent_Petrol"]]
brent = brent[brent["Tarih"] >= "2021-01-01"]

brent.head()

       Tarih  Brent_Petrol
0 2026-03-01        105.32
1 2026-02-01         72.87
2 2026-01-01         69.32
3 2025-12-01         60.49
4 2025-11-01         62.38

In [17]:
# bist_gida_raw.csv ön işleme

bist_gida = pd.read_csv("bist_gida_raw.csv", encoding="utf-8-sig")

bist_gida["Tarih"] = pd.to_datetime(bist_gida["Tarih"], format="%d.%m.%Y")

bist_gida["BIST_Gıda"] = (
    bist_gida["Şimdi"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
)

bist_gida = bist_gida[["Tarih", "BIST_Gıda"]]
bist_gida = bist_gida[bist_gida["Tarih"] >= "2021-01-01"]

bist_gida.head()

       Tarih  BIST_Gıda
0 2026-03-01   13865.74
1 2026-02-01   14457.32
2 2026-01-01   14702.67
3 2025-12-01   12458.20
4 2025-11-01   11549.91

In [18]:
# bist_kimya_raw.csv ön işleme

bist_kimya = pd.read_csv("bist_kimya_raw.csv", encoding="utf-8-sig")

bist_kimya["Tarih"] = pd.to_datetime(bist_kimya["Tarih"], format="%d.%m.%Y")

bist_kimya["BIST_Kimya"] = (
    bist_kimya["Şimdi"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
)

bist_kimya = bist_kimya[["Tarih", "BIST_Kimya"]]
bist_kimya = bist_kimya[bist_kimya["Tarih"] >= "2021-01-01"]

bist_kimya.head()

       Tarih  BIST_Kimya
0 2026-03-01    15066.45
1 2026-02-01    14539.96
2 2026-01-01    15401.81
3 2025-12-01    12791.02
4 2025-11-01    13063.35

In [19]:
# bist_ulastirma_raw.csv ön işleme

bist_ulastirma = pd.read_csv("bist_ulastirma_raw.csv", encoding="utf-8-sig")

bist_ulastirma["Tarih"] = pd.to_datetime(bist_ulastirma["Tarih"], format="%d.%m.%Y")

bist_ulastirma["BIST_Ulaştırma"] = (
    bist_ulastirma["Şimdi"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
)

bist_ulastirma = bist_ulastirma[["Tarih", "BIST_Ulaştırma"]]
bist_ulastirma = bist_ulastirma[bist_ulastirma["Tarih"] >= "2021-01-01"]

bist_ulastirma.head()

       Tarih  BIST_Ulaştırma
0 2026-03-01        36128.09
1 2026-02-01        38111.92
2 2026-01-01        38746.53
3 2025-12-01        34500.04
4 2025-11-01        35096.32

In [20]:
# tahvil_5_yillik_raw.csv ön işleme

tahvil_5y = pd.read_csv("tahvil_5_yillik_raw.csv", encoding="utf-8-sig")

tahvil_5y["Tarih"] = pd.to_datetime(tahvil_5y["Tarih"], format="%d.%m.%Y")

tahvil_5y["Tahvil_5Y_Faizi"] = (
    tahvil_5y["Şimdi"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
)

tahvil_5y = tahvil_5y[["Tarih", "Tahvil_5Y_Faizi"]]
tahvil_5y = tahvil_5y[tahvil_5y["Tarih"] >= "2021-01-01"]

tahvil_5y.head()

       Tarih  Tahvil_5Y_Faizi
0 2026-03-01            36.15
1 2026-02-01            30.98
2 2026-01-01            30.23
3 2025-12-01            30.91
4 2025-11-01            32.47

In [21]:
# tüm verileri birleştirme

tarih_iskeleti = pd.DataFrame({
    "Tarih": pd.date_range("2021-01-01", "2026-03-01", freq="MS")
})

birlesik_veri = (
    tarih_iskeleti
    .merge(tufe, on="Tarih", how="left")
    .merge(politika, on="Tarih", how="left")
    .merge(mevduat, on="Tarih", how="left")
    .merge(dolar, on="Tarih", how="left")
    .merge(altin, on="Tarih", how="left")
    .merge(bist, on="Tarih", how="left")
    .merge(brent, on="Tarih", how="left")
    .merge(bist_gida, on="Tarih", how="left")
    .merge(bist_kimya, on="Tarih", how="left")
    .merge(bist_ulastirma, on="Tarih", how="left")
    .merge(tahvil_5y, on="Tarih", how="left")
)

birlesik_veri.head()

,Tarih,TÜFE_Yıllık_Değişim,TÜFE_Aylık_Değişim,Politika_Faizi,Mevduat_Faizi,USDTRY,Gram_Altın,BIST100,Brent_Petrol,BIST_Gıda,BIST_Kimya,BIST_Ulaştırma,Tahvil_5Y_Faizi
0,2021-01-01,14.97,1.68,17.0,16.36,7.39,449.12,1473.45,55.04,2126.55,1920.05,1635.58,12.93
1,2021-02-01,15.61,0.91,17.0,16.22,7.07,413.65,1471.39,64.42,2004.86,2092.83,1845.28,13.48
2,2021-03-01,16.19,1.08,19.0,16.81,7.63,423.38,1391.73,62.74,1968.79,2111.92,1749.93,18.06
3,2021-04-01,17.14,1.68,19.0,17.78,8.16,464.33,1397.82,66.76,2023.13,2050.88,1688.19,17.87
4,2021-05-01,16.59,0.89,19.0,17.89,8.34,501.26,1420.49,68.95,1944.50,2032.19,1853.87,18.22

In [22]:
# birleşik veri kontrolü

print(birlesik_veri.shape)
print(birlesik_veri.isna().sum())

birlesik_veri.head()
birlesik_veri.tail()

(63, 13)
Tarih                  0
TÜFE_Yıllık_Değişim    1
TÜFE_Aylık_Değişim     1
Politika_Faizi         1
Mevduat_Faizi          0
USDTRY                 0
Gram_Altın             1
BIST100                0
Brent_Petrol           0
BIST_Gıda              0
BIST_Kimya             0
BIST_Ulaştırma         0
Tahvil_5Y_Faizi        0
dtype: int64

,Tarih,TÜFE_Yıllık_Değişim,TÜFE_Aylık_Değişim,Politika_Faizi,Mevduat_Faizi,USDTRY,Gram_Altın,BIST100,Brent_Petrol,BIST_Gıda,BIST_Kimya,BIST_Ulaştırma,Tahvil_5Y_Faizi
58,2025-11-01,31.07,0.87,39.5,46.90,42.18,5764.62,10898.70,62.38,11549.91,13063.35,35096.32,32.47
59,2025-12-01,30.89,0.89,38.0,45.91,42.59,6030.79,11261.52,60.49,12458.20,12791.02,34500.04,30.91
60,2026-01-01,30.65,4.84,37.0,44.62,43.11,6817.67,13838.29,69.32,14702.67,15401.81,38746.53,30.23
61,2026-02-01,31.53,2.96,37.0,43.72,43.59,7515.92,13717.81,72.87,14457.32,14539.96,38111.92,30.98
62,2026-03-01,NaN,NaN,NaN,44.62,44.06,NaN,12698.19,105.32,13865.74,15066.45,36128.09,36.15

In [23]:
birlesik_veri = birlesik_veri.dropna().reset_index(drop=True)

In [24]:
print(birlesik_veri.shape)
print(birlesik_veri.isna().sum())
birlesik_veri.tail()

(62, 13)
Tarih                  0
TÜFE_Yıllık_Değişim    0
TÜFE_Aylık_Değişim     0
Politika_Faizi         0
Mevduat_Faizi          0
USDTRY                 0
Gram_Altın             0
BIST100                0
Brent_Petrol           0
BIST_Gıda              0
BIST_Kimya             0
BIST_Ulaştırma         0
Tahvil_5Y_Faizi        0
dtype: int64

,Tarih,TÜFE_Yıllık_Değişim,TÜFE_Aylık_Değişim,Politika_Faizi,Mevduat_Faizi,USDTRY,Gram_Altın,BIST100,Brent_Petrol,BIST_Gıda,BIST_Kimya,BIST_Ulaştırma,Tahvil_5Y_Faizi
57,2025-10-01,32.87,2.55,39.5,48.13,41.73,5744.17,10971.52,64.77,11914.43,13696.51,37054.70,33.41
58,2025-11-01,31.07,0.87,39.5,46.90,42.18,5764.62,10898.70,62.38,11549.91,13063.35,35096.32,32.47
59,2025-12-01,30.89,0.89,38.0,45.91,42.59,6030.79,11261.52,60.49,12458.20,12791.02,34500.04,30.91
60,2026-01-01,30.65,4.84,37.0,44.62,43.11,6817.67,13838.29,69.32,14702.67,15401.81,38746.53,30.23
61,2026-02-01,31.53,2.96,37.0,43.72,43.59,7515.92,13717.81,72.87,14457.32,14539.96,38111.92,30.98

In [25]:
# temiz veri setini kaydetme

birlesik_veri.to_csv("Analiz_Veri_Seti_Temiz.csv", index=False, encoding="utf-8-sig", sep=";")